import 'package:cloud_firestore/cloud_firestore.dart';

class OrderList {
  final String status,
      deliveryTime,
      deliveryDate,
      receivedTime,
      receivedDate,
      orderNumber,
      senderId,
      senderPhone,
      senderLocation,
      receiverPhone,
      receiverLocation,
      packageType,
      deliveryType,
      orderType,
      packageWeight,
      packageValue,
      servicePhone,
      price,
      paymentMethod,
      driverNumber;
  final GeoPoint senderCoordinates, receiverCoordinates;

  const OrderList(
      {this.status,
      this.deliveryTime,
      this.deliveryDate,
      this.receivedTime,
      this.receivedDate,
      this.orderNumber,
      this.senderId,
      this.senderPhone,
      this.senderLocation,
      this.receiverPhone,
      this.receiverLocation,
      this.packageType,
      this.deliveryType,
      this.orderType,
      this.packageWeight,
      this.packageValue,
      this.servicePhone,
      this.price,
      this.paymentMethod,
      this.driverNumber,
      this.senderCoordinates,
      this.receiverCoordinates});

  factory OrderList.fromJson(Map<String, dynamic> json) {
    return OrderList(
      packageWeight: json['packageWeight'] as String,
      status: json['status'] as String,
      deliveryTime: json['deliveryTime'] as String,
      deliveryDate: json['deliveryDate'] as String,
      receivedTime: json['receivedTime'] as String,
      receivedDate: json['receivedDate'] as String,
      orderNumber: json['orderNumber'] as String,
      senderId: json['senderId'] as String,
      senderPhone: json['senderPhone'] as String,
      senderLocation: json['senderLocation'] as String,
      receiverPhone: json['receiverPhone'] as String,
      receiverLocation: json['receiverLocation'] as String,
      packageType: json['packageType'] as String,
      deliveryType: json['deliveryType'] as String,
      orderType: json['orderType'] as String,
      packageValue: json['packageValue'] as String,
      servicePhone: json['servicePhone'] as String,
      price: json['price'] as String,
      paymentMethod: json['paymentMethod'] as String,
      driverNumber: json['driverNumber'] as String,
      senderCoordinates: json['senderCoordinates'] as GeoPoint,
      receiverCoordinates: json['receiverCoordinates'] as GeoPoint,
    );
  }
}
